name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ProjectSetup

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ProjectSetup.sln

      - name: Build
        run: dotnet build ProjectSetup.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ProjectSetup.sln --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish ProjectSetup.sln --configuration Release --no-restore --no-build