<Project Sdk="Microsoft.NET.Sdk.Web">
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Scalar.AspNetCore" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\..\aspire\Mastery.ServiceDefaults\Mastery.ServiceDefaults.csproj" />
      <ProjectReference Include="..\..\Common\Mastery.Common.ApplicationBus\Mastery.Common.ApplicationBus.csproj" />
      <ProjectReference Include="..\..\Common\Mastery.Common.Database\Mastery.Common.Database.csproj" />
      <ProjectReference Include="..\..\Common\Mastery.Common.Endpoints\Mastery.Common.Endpoints.csproj" />
    </ItemGroup>
    
</Project>
