<Project Sdk="Microsoft.NET.Sdk.Web">
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Scalar.AspNetCore" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\..\aspire\Mastery.ServiceDefaults\Mastery.ServiceDefaults.csproj" />
      <ProjectReference Include="..\..\Modules\Assistant\Mastery.Assistant.Infrastructure\Mastery.Assistant.Infrastructure.csproj" />
    </ItemGroup>
    
</Project>
