<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.1.0"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>a3b76c5f-bf16-4824-9f77-3330f57f28a7</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost"/>
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Api\Mastery.Api\Mastery.Api.csproj" />
      <ProjectReference Include="..\..\src\Common\Mastery.Common.ApplicationBus\Mastery.Common.ApplicationBus.csproj" />
      <ProjectReference Include="..\..\src\Common\Mastery.Common.Database\Mastery.Common.Database.csproj" />
      <ProjectReference Include="..\..\src\Common\Mastery.Common.Endpoints\Mastery.Common.Endpoints.csproj" />
    </ItemGroup>

</Project>
