<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mastery.Assistant.Application\Mastery.Assistant.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="GigaChat.SemanticKernel" />
    </ItemGroup>

</Project>
